# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ShowLibInterface_pb2 as ShowLibInterface__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.InsertRCHashRecord = channel.unary_unary(
        '/ShowLibInterface.Greeter/InsertRCHashRecord',
        request_serializer=ShowLibInterface__pb2.RCHashRecord.SerializeToString,
        response_deserializer=ShowLibInterface__pb2.Result.FromString,
        )
    self.InsertRCHashRecords = channel.stream_stream(
        '/ShowLibInterface.Greeter/InsertRCHashRecords',
        request_serializer=ShowLibInterface__pb2.RCHashRecord.SerializeToString,
        response_deserializer=ShowLibInterface__pb2.Result.FromString,
        )
    self.GetRCHashCount = channel.unary_unary(
        '/ShowLibInterface.Greeter/GetRCHashCount',
        request_serializer=ShowLibInterface__pb2.Result.SerializeToString,
        response_deserializer=ShowLibInterface__pb2.RecordCount.FromString,
        )
    self.GetRCHashRecords = channel.unary_stream(
        '/ShowLibInterface.Greeter/GetRCHashRecords',
        request_serializer=ShowLibInterface__pb2.Result.SerializeToString,
        response_deserializer=ShowLibInterface__pb2.RCHashRecord.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def InsertRCHashRecord(self, request, context):
    """插入一条
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InsertRCHashRecords(self, request_iterator, context):
    """批量插入数据
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRCHashCount(self, request, context):
    """获取RCHash记录数
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRCHashRecords(self, request, context):
    """获取RCHash记录
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'InsertRCHashRecord': grpc.unary_unary_rpc_method_handler(
          servicer.InsertRCHashRecord,
          request_deserializer=ShowLibInterface__pb2.RCHashRecord.FromString,
          response_serializer=ShowLibInterface__pb2.Result.SerializeToString,
      ),
      'InsertRCHashRecords': grpc.stream_stream_rpc_method_handler(
          servicer.InsertRCHashRecords,
          request_deserializer=ShowLibInterface__pb2.RCHashRecord.FromString,
          response_serializer=ShowLibInterface__pb2.Result.SerializeToString,
      ),
      'GetRCHashCount': grpc.unary_unary_rpc_method_handler(
          servicer.GetRCHashCount,
          request_deserializer=ShowLibInterface__pb2.Result.FromString,
          response_serializer=ShowLibInterface__pb2.RecordCount.SerializeToString,
      ),
      'GetRCHashRecords': grpc.unary_stream_rpc_method_handler(
          servicer.GetRCHashRecords,
          request_deserializer=ShowLibInterface__pb2.Result.FromString,
          response_serializer=ShowLibInterface__pb2.RCHashRecord.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ShowLibInterface.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
